// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// coverage_cpp
void coverage_cpp(std::string bedAFile, std::string bedBFile, CharacterVector options);
RcppExport SEXP yCrypticRNAs_coverage_cpp(SEXP bedAFileSEXP, SEXP bedBFileSEXP, SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type bedAFile(bedAFileSEXP);
    Rcpp::traits::input_parameter< std::string >::type bedBFile(bedBFileSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type options(optionsSEXP);
    coverage_cpp(bedAFile, bedBFile, options);
    return R_NilValue;
END_RCPP
}
